---
title: "Shinny Apps"
theme: "rita_theme.css"
---

#### Here is a summary the shinny apps I created. To view details, click on the link. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(kableExtra)
```

```{r}
Date<-c("2021-10","20201-11")
```

```{r}
Apps<-c("A shinny app to billboard ranking",
           "A Shinny App for Housing Lending Prediction")
```

```{r}
Description<-c("For this shinny app, we can select performer and then their individual songs to see how that song ranked in billboard in 2021.",
               "This shinny app will allow users to select features for a house and show the Ceteris Perabus Profile plot of a lasso model that predicts the condition of the house.")
```

```{r}
app_link = c("https://ritaliu6.shinyapps.io/billboard_shinny/",
          "https://ritaliu6.shinyapps.io/05_assignment_shiny/")
```

```{r}
Github_link = c("https://github.com/RitaLiu6/Stat456_Assignment4_shinny",
             "https://github.com/RitaLiu6/05_assignment_shiny")
```

```{r}
data.frame(cbind(Date,Apps,Description,GitHub_Repo = "GitHub Repo")) %>% 
  kbl() %>% 
  kable_styling(full_width = T) %>% 
  column_spec(1,width = "10em") %>% 
  column_spec(2:3,width = "30em") %>% 
  column_spec(2, link=app_link) %>% 
  column_spec(4, link = Github_link)
```